# Generated by Django 4.0.5 on 2022-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='files',
            field=models.FileField(max_length=200, null=True, upload_to=None),
        ),
    ]
